JWT_SECRET_KEY: ""
OPENAI_API_KEY: ""
LLM_MODEL: "gpt-3.5-turbo"
# set this to true to save on tokens during debugging
DUMMY_MODEL: false

# INCARNET_FILE_DIR: /srv/incarnet/storage
# BCRYPT_LOG_ROUNDS: 13
