"""empty message

Revision ID: 600edc52afb6
Revises: c688bcb89d43
Create Date: 2023-12-10 21:19:57.732809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600edc52afb6'
down_revision = 'c688bcb89d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('scan_date')

    # ### end Alembic commands ###
